######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 12 14:03:43 2012
######################################################################

TEMPLATE = app
TARGET = XvcGui
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += XVCalc.h XvcWindow.h
FORMS += XvcWindow.ui
SOURCES += XvcGui.cpp XvcWindow.cpp
LIBS += -L. -lxvcalc
