// Do not use this file while building or linking with Siliko.
// Instead, use the file generated by CMake.

// Put siliko/siliko/include-ide in your IDE's include search list
// so that this file resolves as Siliko/Api.h to eliminate errors from
// missing the header file Siliko/Api.h.

#define SILIKO_EXPORT
#define SILIKO_NO_EXPORT
#define SILIKO_DEPRECATED
#define SILIKO_DEPRECATED_EXPORT
#define SILIKO_DEPRECATED_NO_EXPORT
#define SILIKO_NO_DEPRECATED
