// Do not use this file while building or linking with Siliko.
// Instead, use the file generated by CMake.

// Put siliko/siliko/include-ide in your IDE's include search list
// so that this file resolves as Siliko/Api.h to eliminate errors from
// missing the header file Siliko/Api.h.

#define SILIKOCORE_EXPORT
#define SILIKOCORE_NO_EXPORT
#define SILIKOCORE_DEPRECATED
#define SILIKOCORE_DEPRECATED_EXPORT
#define SILIKOCORE_DEPRECATED_NO_EXPORT
#define SILIKOCORE_NO_DEPRECATED
